# Generated by Django 3.0.5 on 2020-08-14 09:40

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('hostel_delivery', 'hostel_delivery'), ('meal_at_overdose', 'meal_at_overdose')], default='hostel_delivery', max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('available', models.BooleanField(default=True)),
                ('seats', models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.TextField()),
                ('amount', models.PositiveIntegerField()),
                ('placed', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery', models.CharField(choices=[('hostel_delivery', 'hostel_delivery'), ('meal_at_overdose', 'meal_at_overdose')], max_length=25)),
                ('paid', models.BooleanField()),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Not_Confirmed', 'Not_Confirmed')], default='Not_Confirmed', max_length=25)),
                ('OrderBy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slottime', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Overdose.Slot')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Overdose.Item')),
            ],
        ),
    ]
