# Generated by Django 3.0.5 on 2020-08-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overdose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(null=True),
        ),
    ]
