# Generated by Django 3.0.5 on 2020-08-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overdose', '0003_auto_20200814_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
