# Generated by Django 3.0.5 on 2020-08-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overdose', '0004_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Not_Confirmed', 'Not_Confirmed')], default='None', max_length=25),
        ),
    ]
