# Generated by Django 3.0.5 on 2020-08-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overdose', '0007_auto_20200819_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='order_id',
            field=models.PositiveIntegerField(),
        ),
    ]
