# Generated by Django 3.0.5 on 2020-08-19 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overdose', '0008_auto_20200819_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='seats',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
