# Generated by Django 3.0.5 on 2020-08-20 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Overdose', '0009_auto_20200819_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.CharField(choices=[('Cancel', 'Cancel_by_user')], default='None', max_length=25),
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('items', models.TextField()),
                ('amount', models.PositiveIntegerField()),
                ('placed', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery', models.CharField(choices=[('hostel_delivery', 'hostel_delivery'), ('meal_at_overdose', 'meal_at_overdose')], max_length=25)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Not_Confirmed', 'Not_Confirmed')], default='None', max_length=25)),
                ('cancel', models.CharField(choices=[('Cancel', 'Cancel_by_user')], default='None', max_length=25)),
                ('OrderBy', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slottime', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Overdose.Slot')),
            ],
        ),
    ]
