# Generated by Django 3.0.5 on 2020-08-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overdose', '0010_auto_20200820_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancel',
            name='cancel',
        ),
        migrations.AlterField(
            model_name='cancel',
            name='OrderBy',
            field=models.CharField(max_length=50),
        ),
    ]
