# Generated by Django 3.0.5 on 2020-08-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Overdose', '0011_auto_20200820_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cancel',
        ),
    ]
